### ISSUE TITLE
Form instrumentation broken since IC-223.4884-EAP-CANDIDATE-SNAPSHOT

### ISSUE THREAD

**Issue by hstaudacher** [JetBrains/gradle-intellij-plugin#1213]
**Describe the bug**
We are using forms in our intellij plugin together with a gradle build. The `text` property of `JBLabels` will be applied using a resource bundle. This mechanism worked using the intellij gradle plugin `1.5.2` till ideVersion `IC-222.4167-EAP-CANDIDATE-SNAPSHOT`. Since ideVersion `IC-223.4884-EAP-CANDIDATE-SNAPSHOT` till latest RC this mechanism is broken. Strings will not be displayed in the ui. Even hardcoding string does not work. See the screen shot below. The inspector should show a hardcoded value `TEST` but it's empty. We also tried all gradle plugin version including `1.11.0-SNAPSHOT`.

<img width="1433" alt="Screenshot 2022-11-22 at 16 49 39" src="https://user-images.githubusercontent.com/289648/203362811-42228d73-cbbb-4ee5-a7f3-027186ff8174.png">

**To Reproduce**
In a plugin use a form with a JBLabel setting the text property. Build the plugin using the intellij gradle plugin and ideVersion >= `IC-223.4884-EAP-CANDIDATE-SNAPSHOT`

**Expected behavior**
JBLabel should display the text

**Environment:**
 - OS: all 
 - Gradle IntelliJ Plugin Version: 1.5.2 - 1.11.0-SNAPSHOT
 - Gradle Version: 7.5.1

**Additional context**
This is the corresponding [thread on slack](https://jetbrains-platform.slack.com/archives/CPL5291JP/p1669042659450829).

**Comment by hstaudacher** [comment]
Hey guys,
do you plan to do something about this regression any time soon? Thanks for answering.

**Comment by hsz** [comment]
@hstaudacher Can you please try the `1.11.1-SNAPSHOT`? There's a slight change in task caching – maybe that'd help.
If not, I'll go with further investigation.

**Comment by hstaudacher** [comment]
Thanks @hsz. I just tested `1.11.1-SNAPSHOT` and it does fix the problem.

**Comment by hsz** [comment]
Awesome, than you for the confirmation!

**Comment by hsz** [comment]
This may still be caused by the Gradle configuration cache (#1283). It turned out that the instrumented classes aren't considered when building the output `jar` file after the project configuration is evaluated and stored — it falls back to the "pure" compiled classes instead.

I pushed a fix for that this morning — it is available via the `1.12.1-SNAPSHOT`. Can you give it a try?

**Comment by hstaudacher** [comment]
Sadly this doesn't fix the problem. It leads to a broken plugin version for 222, 223 and 231.

**Comment by hsz** [comment]
After the direct discussion, it turned out it's related to the multi-module project type. Will work if it soon.

**Comment by hsz** [comment]
The instrumentation is reworked, but it turned out that since `2022.3`, components from the `JB*` family aren't instrumented properly, and labels set via UI Designer are missing.
As a workaround, it's advised to:
- switch to regular components, like `JBCheckBox` -> `JCheckBox`
- or set the component's text programmatically in the class constructor

**Comment by hsz** [comment]
After further debugging, it turns out that `JB*` components get ignored after switching to `2022.3+` IJ SDK when still having Java 11 in use. After switching to Java 17 — which is actually required for `2022.3+` — UI should be rendered properly.

@hstaudacher please confirm that.

**Comment by hstaudacher** [comment]
Confirmed. We use Java 17 to build but had this in our gradle file:

```
        withType<JavaCompile> {
            sourceCompatibility = "11"
            targetCompatibility = "11"
        }
```
